In [1]:
print('Ritu')

Ritu


In [2]:
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [3]:
X,y = load_diabetes(return_X_y = True)

In [4]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [5]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 2)

In [6]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(353, 10)
(353,)
(89, 10)
(89,)


In [7]:
lr = LinearRegression()

In [8]:
lr.fit(X_train,y_train)

LinearRegression()

In [9]:
predict = lr.predict(X_test)

In [10]:
predict

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [11]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [12]:
lr.intercept_

np.float64(151.88331005254167)

In [13]:
class GDRegressor:
    def __init__(self,epochs = 100,learning_rate = 0.01):
        self.coef_ = None
        self.intercept_ = None
        self.epochs = epochs
        self.learning_rate = learning_rate

    def fit(self,X_train,y_test):
        self.intercept_= 0
        self.coef_ = np.ones(X_train.shape[1])

        for i in range(self.epochs):
            y_hat = self.intercept_ + np.dot(X_train,self.coef_)
            self.intercept_ = self.intercept_ - self.learning_rate*(-2*np.mean(y_train - y_hat)) 

            self.coef_ = self.coef_ - self.learning_rate*(-2*np.dot((y_train - y_hat),X_train)/X_train.shape[0])

    def predict(self,X_test):
        return np.dot(X_test,self.coef_)+self.intercept_

In [18]:
gd = GDRegressor(epochs = 1000,learning_rate = .5)

In [19]:
gd.fit(X_train,y_train)

In [22]:
gdpredict = gd.predict(X_test)
gdpredict

array([152.26392304, 198.96222354, 127.66111541, 104.59596478,
       265.23062371, 252.09467525, 112.76592254, 115.72549839,
        96.37765691, 187.64845451, 144.9482918 , 172.110596  ,
       178.81497695, 136.51444368, 292.15564227,  87.25795061,
       202.18473262, 149.11155912, 132.30895031, 128.70828962,
       148.38757935, 171.81318343, 150.93593445, 174.47559507,
       127.76388814, 221.82234243, 199.96855698, 101.54518353,
        54.85644772, 237.61948938, 244.2801351 , 112.91877003,
        68.12192242,  96.00468527, 204.32975531, 163.99882781,
       160.95172334, 191.90398957, 113.33794145, 238.46002509,
       141.40211434, 120.45598718, 188.12639096, 186.46474321,
       174.98259299, 143.24561624, 168.80798895, 299.18508813,
       105.40854525, 169.51466009, 254.37509674, 142.60026818,
       151.7158263 , 122.70403085, 191.52875115,  94.27792144,
       129.03875584,  75.96073902, 157.91752518, 156.36603694,
       163.20324594, 160.93274887, 102.3002858 , 227.76

In [20]:
print('gd.coef_ = ',gd.coef_,'\ngd.intercept_ = ',gd.intercept_)

gd.coef_ =  [  14.38990585 -173.7235727   491.54898524  323.91524824  -39.32648042
 -116.01061213 -194.04077415  103.38135565  451.63448787   97.57218278] 
gd.intercept_ =  152.01351687661833


In [21]:
print('lr.coef_ = ',lr.coef_,'\nlr.intercept_ = ',lr.intercept_)

lr.coef_ =  [  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238] 
lr.intercept_ =  151.88331005254167


In [23]:
print('MAE of lr',mean_absolute_error(y_test,predict))
print('MAE of gd',mean_absolute_error(y_test,gdpredict))

MAE of lr 45.21303419046903
MAE of gd 45.37416503009942


In [24]:
print('MSE of lr',mean_squared_error(y_test,predict))
print('MSE of gd',mean_squared_error(y_test,gdpredict))

MSE of lr 3094.4566715660626
MSE of gd 3019.776152429174


In [25]:
print('R2 of lr',r2_score(y_test,predict))
print('R2 of gd',r2_score(y_test,gdpredict))


R2 of lr 0.4399338661568968
R2 of gd 0.4534503034722803
