In [1]:
print('ritu')

ritu


In [2]:
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [3]:
X,y = load_diabetes(return_X_y = True)

In [4]:
X.shape

(442, 10)

In [5]:
y.shape

(442,)

# SKlearn Linear Regression

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 2)

In [7]:
display(X_train)
display(y_train)
display(X_test)
display(y_test)

array([[-0.00188202, -0.04464164, -0.06979687, ..., -0.03949338,
        -0.06291688,  0.04034337],
       [-0.00914709, -0.04464164,  0.01103904, ..., -0.03949338,
         0.01703607, -0.0052198 ],
       [ 0.02354575,  0.05068012, -0.02021751, ..., -0.03949338,
        -0.09643495, -0.01764613],
       ...,
       [ 0.06350368,  0.05068012, -0.00405033, ..., -0.00259226,
         0.08449153, -0.01764613],
       [-0.05273755,  0.05068012, -0.01806189, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [ 0.00175052,  0.05068012,  0.05954058, ...,  0.1081111 ,
         0.06898589,  0.12732762]])

array([ 48., 276.,  47., 175.,  60.,  81., 242., 197., 137., 129., 138.,
       160., 116., 101., 147., 100., 144.,  69., 219., 107., 168., 236.,
       109., 321., 128.,  43.,  72.,  55., 141., 283.,  59., 150., 346.,
       124., 186., 308., 272., 190.,  63.,  91.,  72.,  65., 158.,  90.,
       185.,  45., 199., 206.,  61., 139., 296., 281., 122.,  95.,  40.,
       127., 145., 108., 185.,  53., 132., 101., 263.,  94., 295., 259.,
       232., 124.,  77., 102.,  96.,  83., 263.,  71., 246.,  66., 115.,
       222.,  93., 129., 128., 163.,  99.,  92., 179., 140.,  94.,  97.,
       174.,  61., 202., 135.,  88., 152.,  69.,  31., 248., 275.,  64.,
        94.,  99., 109.,  90.,  37., 164., 274., 200.,  49., 214.,  85.,
       154., 134., 164., 189.,  64., 150., 245.,  67., 265., 151.,  75.,
       208., 292.,  90.,  59.,  44., 277.,  67.,  72., 182., 135., 275.,
        95., 332., 214.,  53., 141., 102.,  88.,  74., 103., 292.,  70.,
       138., 139.,  98.,  72.,  25.,  72., 264.,  9

array([[ 0.06713621, -0.04464164,  0.00349435,  0.03564379,  0.0493413 ,
         0.03125356,  0.07072993, -0.03949338, -0.00061174,  0.01963284],
       [-0.07816532,  0.05068012,  0.07786339,  0.05285804,  0.07823631,
         0.0644473 ,  0.02655027, -0.00259226,  0.04067283, -0.00936191],
       [ 0.04170844,  0.05068012, -0.01482845, -0.01713512, -0.00569682,
         0.00839372, -0.01394774, -0.00185424, -0.01189685,  0.00306441],
       [-0.04547248, -0.04464164, -0.04824063, -0.01944183, -0.00019301,
        -0.01603186,  0.06704829, -0.03949338, -0.02479543,  0.01963284],
       [ 0.0090156 ,  0.05068012,  0.06924089,  0.05974375,  0.01769438,
        -0.02323427, -0.04708248,  0.03430886,  0.10329702,  0.07348023],
       [ 0.03444337,  0.05068012,  0.12528712,  0.02875809, -0.05385517,
        -0.01290037, -0.10230705,  0.1081111 ,  0.00027248,  0.02791705],
       [-0.03457486, -0.04464164, -0.05901875,  0.00121528, -0.05385517,
        -0.07803525,  0.06704829, -0.0763945 

array([ 73., 233.,  97., 111., 277., 341.,  64.,  68.,  65., 178., 142.,
        77., 244., 115., 258.,  87., 220.,  86.,  74., 132., 136., 220.,
        91., 235., 148., 317., 131.,  84.,  65., 217., 306.,  79., 158.,
        54., 123., 174., 237., 212., 179., 281., 187., 200.,  68., 163.,
       141., 202., 178., 242.,  47., 131., 243., 142., 200.,  89., 232.,
        55., 253., 128., 104., 184., 110., 198.,  81., 195., 150.,  63.,
       151., 233., 178.,  84., 237., 109., 131., 252., 200., 160., 200.,
        51., 111.,  77., 201.,  88.,  78., 243., 268.,  55., 270., 288.,
        91.])

In [8]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(353, 10)
(353,)
(89, 10)
(89,)


In [9]:
lr = LinearRegression()

In [10]:
lr.fit(X_train,y_train)

LinearRegression()

In [11]:
predict = lr.predict(X_test)

In [12]:
for i in range(y_test.shape[0]):
    print('y_test = ',y_test[i],'predict = ',predict[i])

y_test =  73.0 predict =  154.12138809538374
y_test =  233.0 predict =  204.81835117652128
y_test =  97.0 predict =  124.93755352869645
y_test =  111.0 predict =  106.08950892826041
y_test =  277.0 predict =  258.53485759855664
y_test =  341.0 predict =  256.3310074008199
y_test =  64.0 predict =  118.75087616091697
y_test =  68.0 predict =  119.52440696107092
y_test =  65.0 predict =  101.50816734991383
y_test =  178.0 predict =  190.54048660815047
y_test =  142.0 predict =  141.70656811061912
y_test =  77.0 predict =  172.5188396146561
y_test =  244.0 predict =  174.33861648821426
y_test =  115.0 predict =  134.80942706126186
y_test =  258.0 predict =  294.1399453657883
y_test =  87.0 predict =  94.11798038458227
y_test =  220.0 predict =  211.97059794859274
y_test =  86.0 predict =  156.49579378119398
y_test =  74.0 predict =  134.21000428481707
y_test =  132.0 predict =  119.62664644088312
y_test =  136.0 predict =  148.87842251198728
y_test =  220.0 predict =  165.0087340928784
y_

In [13]:
# lr.predict(np.array([73]).reshape(1,1))
lr.predict(X_test[0].reshape(1,10))

array([154.1213881])

In [14]:
print('coef = ',lr.coef_,'\nintercept = ',lr.intercept_)

coef =  [  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238] 
intercept =  151.88331005254167


# Making our own Linear Regression class

In [15]:
class MeraLR:
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis = 1)
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.coef_ = betas[1:]
        self.intercept_ = betas[0]
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [16]:
mlr = MeraLR()

In [17]:
mlr.fit(X_train,y_train)

In [18]:
mpredict = mlr.predict(X_test)

In [19]:
mpredict

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [20]:
mlr.predict(X_test[0])

np.float64(154.12138809538385)

In [21]:
for i in range(y_test.shape[0]):
    print('y_test = ',y_test[i],'mpredict = ',mpredict[i])

y_test =  73.0 mpredict =  154.12138809538385
y_test =  233.0 mpredict =  204.81835117652116
y_test =  97.0 mpredict =  124.93755352869651
y_test =  111.0 mpredict =  106.08950892826053
y_test =  277.0 mpredict =  258.53485759855596
y_test =  341.0 mpredict =  256.33100740082045
y_test =  64.0 mpredict =  118.75087616091687
y_test =  68.0 mpredict =  119.52440696107081
y_test =  65.0 mpredict =  101.50816734991386
y_test =  178.0 mpredict =  190.54048660815056
y_test =  142.0 mpredict =  141.7065681106191
y_test =  77.0 mpredict =  172.51883961465632
y_test =  244.0 mpredict =  174.33861648821474
y_test =  115.0 mpredict =  134.80942706126206
y_test =  258.0 mpredict =  294.13994536578775
y_test =  87.0 mpredict =  94.11798038458235
y_test =  220.0 mpredict =  211.97059794859274
y_test =  86.0 mpredict =  156.49579378119384
y_test =  74.0 mpredict =  134.210004284817
y_test =  132.0 mpredict =  119.62664644088319
y_test =  136.0 mpredict =  148.87842251198708
y_test =  220.0 mpredict =

In [22]:
for i in range(predict.shape[0]):
    print('predict = ',predict[i],'mpredict = ',mpredict[i])

predict =  154.12138809538374 mpredict =  154.12138809538385
predict =  204.81835117652128 mpredict =  204.81835117652116
predict =  124.93755352869645 mpredict =  124.93755352869651
predict =  106.08950892826041 mpredict =  106.08950892826053
predict =  258.53485759855664 mpredict =  258.53485759855596
predict =  256.3310074008199 mpredict =  256.33100740082045
predict =  118.75087616091697 mpredict =  118.75087616091687
predict =  119.52440696107092 mpredict =  119.52440696107081
predict =  101.50816734991383 mpredict =  101.50816734991386
predict =  190.54048660815047 mpredict =  190.54048660815056
predict =  141.70656811061912 mpredict =  141.7065681106191
predict =  172.5188396146561 mpredict =  172.51883961465632
predict =  174.33861648821426 mpredict =  174.33861648821474
predict =  134.80942706126186 mpredict =  134.80942706126206
predict =  294.1399453657883 mpredict =  294.13994536578775
predict =  94.11798038458227 mpredict =  94.11798038458235
predict =  211.97059794859274 

In [23]:
mlr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [24]:
mlr.intercept_

np.float64(151.8833100525417)

In [25]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [26]:
lr.intercept_

np.float64(151.88331005254167)

In [27]:
print('MAE of lr',mean_absolute_error(y_test,predict))
print('MAE of mlr',mean_absolute_error(y_test,mpredict))

MAE of lr 45.21303419046903
MAE of mlr 45.213034190469


In [28]:
print('MSE of lr',mean_squared_error(y_test,predict))
print('MSE of mlr',mean_squared_error(y_test,mpredict))

MSE of lr 3094.4566715660626
MSE of mlr 3094.456671566058


In [29]:
print('R2 of lr',r2_score(y_test,predict))
print('R2 of mlr',r2_score(y_test,mpredict))

R2 of lr 0.4399338661568968
R2 of mlr 0.43993386615689756


In [37]:
mlr.coef_.shape

(10,)

In [38]:
mlr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [41]:
X_train.shape

(353, 10)

In [42]:
X_train.T.shape

(10, 353)